// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GrpcapiEchoResponse grpcapi echo response
// swagger:model grpcapiEchoResponse
type GrpcapiEchoResponse struct {

	// result
	Result string `json:"result,omitempty"`
}

// Validate validates this grpcapi echo response
func (m *GrpcapiEchoResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GrpcapiEchoResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GrpcapiEchoResponse) UnmarshalBinary(b []byte) error {
	var res GrpcapiEchoResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
