// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMessage) Reset()         { *m = TestMessage{} }
func (m *TestMessage) String() string { return proto.CompactTextString(m) }
func (*TestMessage) ProtoMessage()    {}
func (*TestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *TestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMessage.Unmarshal(m, b)
}
func (m *TestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMessage.Marshal(b, m, deterministic)
}
func (m *TestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMessage.Merge(m, src)
}
func (m *TestMessage) XXX_Size() int {
	return xxx_messageInfo_TestMessage.Size(m)
}
func (m *TestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TestMessage proto.InternalMessageInfo

func (m *TestMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

var E_MsgOptionA = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         50011,
	Name:          "grpcapi.msg_option_a",
	Tag:           "varint,50011,opt,name=msg_option_a",
	Filename:      "test.proto",
}

var E_MsgOptionB = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         50012,
	Name:          "grpcapi.msg_option_b",
	Tag:           "varint,50012,opt,name=msg_option_b",
	Filename:      "test.proto",
}

func init() {
	proto.RegisterType((*TestMessage)(nil), "grpcapi.TestMessage")
	proto.RegisterExtension(E_MsgOptionA)
	proto.RegisterExtension(E_MsgOptionB)
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x2f, 0x2a, 0x48, 0x4e, 0x2c, 0xc8, 0x94,
	0x52, 0x48, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x0b, 0x27, 0x95, 0xa6, 0xe9, 0xa7, 0xa4,
	0x16, 0x27, 0x17, 0x65, 0x16, 0x94, 0xe4, 0x17, 0x41, 0x94, 0x2a, 0x69, 0x73, 0x71, 0x87, 0xa4,
	0x16, 0x97, 0xf8, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x0a, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6,
	0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x56, 0x1c, 0x37, 0xb6, 0x4a, 0x88,
	0x3d, 0xd8, 0x2a, 0xa1, 0x68, 0xe5, 0xcc, 0xc5, 0x93, 0x5b, 0x9c, 0x1e, 0x9f, 0x5f, 0x50, 0x92,
	0x99, 0x9f, 0x17, 0x9f, 0x28, 0x24, 0xaf, 0x07, 0x31, 0x5f, 0x0f, 0x66, 0xbe, 0x1e, 0xd4, 0x1c,
	0x7f, 0xb0, 0x8a, 0x62, 0x89, 0xdb, 0x6d, 0xcc, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x5c, 0xb9, 0xc5,
	0xe9, 0x10, 0x31, 0x47, 0x34, 0x43, 0x92, 0x08, 0x1b, 0x72, 0x07, 0xc3, 0x10, 0x27, 0x27, 0x96,
	0x28, 0xa6, 0x82, 0xa4, 0x24, 0x36, 0xb0, 0x16, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x63,
	0x09, 0x2e, 0xa8, 0xfc, 0x00, 0x00, 0x00,
}
