// Copyright 2018 The Vogo Authors. All rights reserved.
// Use of this source code is governed by a Apache license
// that can be found in the LICENSE file.

// Code generated by "makestatic"; DO NOT EDIT.

package api

var ProtoFiles = []string{"0.proto", "auth.proto", "echo.proto", "hello.proto"}
